---
- name: Install required packages
  package:
    name: vsftpd
    state: present
    update_cache: yes

- name: Configure vsftpd service
  service:
    name: vsftpd
    state: started
    enabled: yes

- name: Add nologin shell
  lineinfile:
    state: present
    dest: /etc/shells
    line: "/usr/sbin/nologin"
    regexp: "^/usr/sbin/nologin"
    insertafter: EOF

- name: Create home directory
  file:
    path: "{{ www_path }}/{{ client_username }}/www_data"
    state: directory
    owner: root
    group: root
    mode: 0555
    
- name: Create ftp directory
  file:
    path: "{{ www_path }}/{{ client_username }}/www_data/ftp"
    owner: "{{ client_username }}"
    group: "{{ client_username }}"
    mode: u=rwX,g=rX,o=rX
  when: ftp_only == 'yes'

- name: Add user
  user:
    name: "{{ client_username }}"
    comment: "{{ client_username }}"
    password: "{{ linux_user_pwd }}"
    home: "/var/www/{{ client_username }}/www_data"
    shell: /usr/sbin/nologin

- name: Deploy FTP configuration file
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd.conf
    owner: root
    group: root
    mode:  0644
